//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopAccessApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_order_set_view
    {
        public short status { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public string additional_information { get; set; }
        public decimal order_price { get; set; }
        public string case_model { get; set; }
        public Nullable<int> case_amount { get; set; }
        public Nullable<decimal> case_price { get; set; }
        public string graphics_card_model { get; set; }
        public Nullable<int> graphics_card_amount { get; set; }
        public Nullable<decimal> graphics_card_price { get; set; }
        public string motherboard_model { get; set; }
        public Nullable<int> motherboard_amount { get; set; }
        public Nullable<decimal> motherboard_price { get; set; }
        public string processor_model { get; set; }
        public Nullable<int> processor_amount { get; set; }
        public Nullable<decimal> processor_price { get; set; }
        public string ram_memory_model { get; set; }
        public Nullable<int> ram_memory_amount { get; set; }
        public Nullable<decimal> ram_memory_price { get; set; }
        public string service { get; set; }
        public Nullable<decimal> service_price { get; set; }
    }
}
