//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopAccessApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ram_memories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ram_memories()
        {
            this.client_order_sets = new HashSet<client_order_sets>();
            this.warehouse_orders = new HashSet<warehouse_orders>();
        }
    
        public int id { get; set; }
        public string model { get; set; }
        public string type { get; set; }
        public int capacity_gb { get; set; }
        public decimal price { get; set; }
        public Nullable<int> amount { get; set; }
        public string image_source { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client_order_sets> client_order_sets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<warehouse_orders> warehouse_orders { get; set; }
    }
}
