//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopAccessApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudiaProjektBazyDanychEntities : DbContext
    {
        public StudiaProjektBazyDanychEntities()
            : base("name=StudiaProjektBazyDanychEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cases> cases { get; set; }
        public virtual DbSet<client_order_sets> client_order_sets { get; set; }
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<graphics_cards> graphics_cards { get; set; }
        public virtual DbSet<motherboards> motherboards { get; set; }
        public virtual DbSet<processors> processors { get; set; }
        public virtual DbSet<ram_memories> ram_memories { get; set; }
        public virtual DbSet<Registration> Registration { get; set; }
        public virtual DbSet<services> services { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<warehouse_orders> warehouse_orders { get; set; }
        public virtual DbSet<wholesalers> wholesalers { get; set; }
        public virtual DbSet<client_order_set_view> client_order_set_view { get; set; }
        public virtual DbSet<warehouse_order_view> warehouse_order_view { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
