//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopAccessApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehouse_orders
    {
        public int id { get; set; }
        public int id_wholesaler { get; set; }
        public Nullable<int> id_motherboard { get; set; }
        public Nullable<int> motherboard_amount { get; set; }
        public Nullable<int> id_processor { get; set; }
        public Nullable<int> processor_amount { get; set; }
        public Nullable<int> id_graphics_card { get; set; }
        public Nullable<int> graphics_card_amount { get; set; }
        public Nullable<int> id_case { get; set; }
        public Nullable<int> case_amount { get; set; }
        public Nullable<int> id_ram_memory { get; set; }
        public Nullable<int> ram_memory_amount { get; set; }
        public string additional_information { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public short status { get; set; }
        public decimal order_price { get; set; }
    
        public virtual cases cases { get; set; }
        public virtual graphics_cards graphics_cards { get; set; }
        public virtual motherboards motherboards { get; set; }
        public virtual processors processors { get; set; }
        public virtual ram_memories ram_memories { get; set; }
        public virtual wholesalers wholesalers { get; set; }
    }
}
